sudo: false
language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install tox coveralls

script:
  - nosetests
  - coverage run --source=mail setup.py test
  - coverage report -m

after_success:
  - coveralls
